# Site settings
title: Όμιλος Μαθηματικών και Λογοτεχνίας, 2ο ΠΓΕΛ Αθηνών
email: mathliteratureclub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Όμιλος Μαθηματικών και Λογοτεχνίας του 2ου Πειραματικού Γενικού Λυεκίου Αθηνών
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cnpapado.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other
encoding: utf-8
timezone: Europe/Athens

defaults:
  -
    scope:
      path: "pages/lectures"
      type: "posts" # note that path: "_posts" instead of type: "posts" is for some reason not working
    values:
      layout: "post"
  -
    scope:
      path: "pages/articles"
      type: "posts" 
    values:
      layout: "article" 	  
  -
    scope:
      path: "pages/archive"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "pages/events"
      type: "posts" 
    values:
      layout: "archive"
  -
    scope:
      path: "pages/lectures"
      type: "posts"
    values:
      layout: "post"
