---
title: Όμιλος Μαθηματικών και Λογοτεχνίας, 2ο ΠΓΕΛ Αθηνών
timezone: Europe/Athens
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: pages/articles
    type: posts
  values:
    layout: article
- scope:
    path: pages/archive
    type: posts
  values:
    layout: post
- scope:
    path: pages/events
    type: posts
  values:
    layout: archive
- scope:
    path: pages/lectures
    type: posts
  values:
    layout: post
email: mathliteratureclub@gmail.com
description: 'Όμιλος Μαθηματικών και Λογοτεχνίας του 2ου Πειραματικού Γενικού Λυεκίου
  Αθηνών

'
baseurl: ''
url: https://mathematicsliterature.github.io
markdown: kramdown
encoding: utf-8
