# Site settings
title: Όμιλος Μαθηματικών και Λογοτεχνίας, 2ο ΠΓΕΛ Αθηνών
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cnpapado.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other
encoding: utf-8
timezone: Europe/Athens

defaults:
  -
    scope:
      path: ""
      type: "posts" # note that path: "_posts" instead of type: "posts" is for some reason not working
    values:
      layout: "post"
  -
    scope:
      path: "pages/lectures"
      type: "posts" # note that path: "_posts" instead of type: "posts" is for some reason not working
    values:
      layout: "post"
  -
    scope:
      path: "pages/articles"
      type: "posts" 
    values:
      layout: "article" 	  
  -
    scope:
      path: "pages/archive"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "pages/events"
      type: "posts" 
    values:
      layout: "archive"
  -
    scope:
      path: "pages/lectures"
      type: "posts"
    values:
      layout: "post"
